#spring.application.name=QuerySummarizer

#spring.ai.openai.base-url= https://ollama.com
#spring.ai.openai.chat.model = gpt-oss:120b

spring.application.name=QuerySummarizer

spring.ai.openai.api-key=${OLLAMA_API_KEY}
spring.ai.openai.base-url=https://ollama.com/v1
spring.ai.openai.chat.model=gpt-oss:120b
